### PR TITLE
[WIP] VictoryForce

### PR DESCRIPTION
**Pull request by nfcampos**
- [x] add a demo
- [x] render links
- [x] rename `nodes` prop to `data` for consistency?
- [x] pass `style` and `events` prop to `VictoryScatter` (depends on above)
- [ ] add `domainPadding` prop
- [ ] make an example with labels
- [ ] `parent` events are probably not working
- [ ] pass through `alphaTarget`, `alphaMin`, `velocityDecay` props to simulation

### CODE REVIEW

**Comment by nfcampos** [comment]
@boygirl after a long pause I've finally came back to work on this. I've added a demo 🎉 loosely based on this http://bl.ocks.org/mbostock/95aa92e2f4e8345aaa55a4a94d41ce37
I ended up rendering the links with another `VictoryScatter` with a custom `dataComponent`, for now it's a bit hacky as VictoryScatter has no concept of `x2`, `y2`
I want to add another example with events soon.
for now can you tell me what you think of the api of the `VictoryForce` component like this? And any other comments are more than welcome :)

**Comment by nfcampos** [comment]
I've added a click event to the demo, try clicking the nodes :)

**Comment by boygirl** [comment]
@nfcampos Awesome! I have a couple other things to wrap up first, but I'll carve out some time for a review in the next day or two. Thanks for building this!

**Comment by boygirl** [comment]
The demo is looking so good! I would definitely like to spend some time seeing how many of the patterns we can re-use from other victory code just to keep everything consistent. It's also a little problematic that this need to take a dependency on VictoryChart in order to use VictoryScatter. That works for now, but I think we will end up writing something purpose built in this repo.

**Comment by nfcampos** [comment]
One thing I thought about that might make sense is for victory-core to include a `VictoryXY` component that does all the stuff related to charts with x and y dimensions — event handling, computing domains, scales, etc., rendering labelComponent for the labels, rendering dataComponent for the data points. Then VictoryBar, VictoryScatter, VictoryForce could just all use that with a custom `dataComponent`.
In the end it'd be pretty similar to eg. VictoryScatter but instead of taking x, y, size, etc. props it could take an `accessors` prop like `{x: 'x', y: datum => datum.y, y2: datum => datum.y2}` and what's defined in that accessor prop is what's gets passed to `dataComponent`. What do you think?

**Comment by boygirl** [comment]
I think I can do some work in the next Victory release (end of the month) to support you. _i.e._ moving all the chart primitives like Point and Line to the victory-core repo, as well as some methods you'll need like `getDomain`. I think the best course of action at this point would be to merge what you've got, and focus on writing a for purpose component for the nodes rather than using VictoryScatter. Keep depending on VictoryChart, and see what you end up needing from that repo to get it done.

**Comment by boygirl** [comment]
My only comment about the API so far is that maybe `nodes` should be a prop rather than `data` to match the language people normally use for force layouts. Or if `data` remains a prop, maybe `nodes` and `links` can be pulled from data with accessor props as in other components.

**Comment by boygirl** [comment]
hmmm. there's a little more that's different between the chart types than just the data component unfortunately. I think my preference would be to just keep anything that needs an axis in the chart repo. Force is different enough that it deserves it's own repo, but I can see extracting some of what lives in chart to victory-core to support it

**Comment by nfcampos** [comment]
is there anything other than
- dataComponent
- props passed to dataComponent
- keys passed to dataComponent inside style prop

that is different between eg VictoryBar and VictoryScatter?

**Comment by boygirl** [comment]
VictoryLine, VictoryArea and VictoryBar just got clipPath added to support they way they transition when new data points animate in. VictoryBar and VictoryArea both need domains that start at 0 by default. VictoryLine and VictoryArea only render a single continuous data element. VictoryCandlestick and VictoryErrorBar have unique data props etc etc. They're actually annoyingly different.

**Comment by nfcampos** [comment]
yeah i guess they're different enough, but there is plenty of code that is exactly the same for all of those, and will be the same for VictoryForce

**Comment by boygirl** [comment]
Yeah, definitely worth extracting the same parts. I'll see what I can do.

**Comment by nfcampos** [comment]
@boygirl I've renamed `data` to `nodes`.
Should I merge this in now like you said?
For writing the custom component for this I think I'll at least need the Domain and Scale helpers from victory-chart

**Comment by boygirl** [comment]
@nfcampos yes, you can merge this. It will be easier to work in smaller branches and this is looking like a really solid v1.

I extracted all the primitive components like `Line`, `Point` etc into `victory-core`, but I think you're right that that basic scale / domain helpers need to live there too. I'll get that in for you in the next week-ish.

**Pull request merged**
